from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol

class Cursor(Protocol):
    description: tuple[Any, ...] | None
    rowcount: int
    lastrowid: int

    async def execute(self, query: str, args: Any = None) -> int: ...
    async def executemany(self, query: str, args: Sequence[Any]) -> int | None: ...
    async def fetchone(self) -> tuple[Any, ...] | None: ...
    async def fetchmany(self, size: int | None = None) -> Sequence[tuple[Any, ...]]: ...
    async def fetchall(self) -> Sequence[tuple[Any, ...]]: ...
    async def close(self) -> None: ...
