"""Schema diff — compare two schema snapshots and produce change operations."""

from __future__ import annotations

import dataclasses

from nextorm.schema.core import Column, Index, Table

__all__ = [
    "CreateTable",
    "DropTable",
    "AddColumn",
    "DropColumn",
    "AlterColumnType",
    "AddIndex",
    "DropIndex",
    "SchemaOp",
    "diff_schemas",
]


@dataclasses.dataclass
class CreateTable:
    table: Table


@dataclasses.dataclass
class DropTable:
    table_name: str


@dataclasses.dataclass
class AddColumn:
    table_name: str
    column: Column


@dataclasses.dataclass
class DropColumn:
    table_name: str
    column_name: str


@dataclasses.dataclass
class AlterColumnType:
    """Change the SQL type of an existing column.

    Generated by :func:`diff_schemas` when a column's Python type or a
    type-influencing :class:`~nextorm.schema.core.Column` attribute (e.g.
    ``max_len``, ``precision``, ``scale``) differs between *current* and
    *target*.

    Attributes
    ----------
    table_name:
        Name of the table containing the column.
    column:
        The *target* column descriptor (carries the new type information).
    """

    table_name: str
    column: Column


@dataclasses.dataclass
class AddIndex:
    table_name: str
    index: Index


@dataclasses.dataclass
class DropIndex:
    table_name: str
    index_name: str


type SchemaOp = (
    CreateTable | DropTable | AddColumn | DropColumn | AlterColumnType | AddIndex | DropIndex
)  # noqa: UP040


def _column_type_changed(cur: Column, tgt: Column) -> bool:
    """Return ``True`` if any type-determining attribute of *cur* differs from *tgt*.

    Compares the attributes that DDL renderers inspect when deciding the SQL
    type for a column.  Non-type attributes (``primary_key``, ``index``,
    ``auto_increment``, ``sql_default``) are intentionally excluded — they
    are controlled by separate DDL operations.

    When *cur* has ``py_type=object`` (the sentinel written by introspectors
    that cannot reconstruct a Python type from the live schema), the Python
    type and all numeric type-modifiers are considered unknown and are
    therefore excluded from the comparison.  Only ``nullable`` is still
    checked in that case because it *is* recoverable from ``NOT NULL``.
    """
    if cur.py_type is object:
        # Live-schema sentinel: py_type and size/precision/scale/unsigned/
        # dimensions/max_len/sql_type_override are unknown — skip them.
        return cur.nullable != tgt.nullable
    return (
        cur.py_type != tgt.py_type
        or cur.max_len != tgt.max_len
        or cur.precision != tgt.precision
        or cur.scale != tgt.scale
        or cur.nullable != tgt.nullable
        or cur.unique != tgt.unique
        or cur.sql_type_override != tgt.sql_type_override
        or cur.unsigned != tgt.unsigned
        or cur.size != tgt.size
        or cur.dimensions != tgt.dimensions
    )


def diff_schemas(
    current: dict[str, Table],
    target: dict[str, Table],
) -> list[SchemaOp]:
    """Return the ordered list of operations that evolve *current* into *target*.

    Detects:

    * New tables → ``CreateTable``
    * Dropped tables → ``DropTable``
    * New columns → ``AddColumn``
    * Dropped columns → ``DropColumn``
    * Column type changes (``py_type``, ``max_len``, ``precision``, ``scale``,
      ``nullable``, ``unique``, ``sql_type_override``) → ``AlterColumnType``
    * New indexes → ``AddIndex``
    * Dropped indexes → ``DropIndex``
    """
    ops: list[SchemaOp] = []

    # Tables that appear in target but not in current → CREATE
    for name, table in target.items():
        if name not in current:
            ops.append(CreateTable(table))

    # Tables present in current but absent from target → DROP
    for name in current:
        if name not in target:
            ops.append(DropTable(name))

    # Tables present in both → diff columns and indexes
    for name in target:
        if name not in current:
            continue
        cur = current[name]
        tgt = target[name]

        cur_cols = {c.name: c for c in cur.columns}
        tgt_cols = {c.name: c for c in tgt.columns}

        for col_name, col in tgt_cols.items():
            if col_name not in cur_cols:
                ops.append(AddColumn(name, col))
            else:
                cur_col = cur_cols[col_name]
                if _column_type_changed(cur_col, col):
                    ops.append(AlterColumnType(name, col))

        for col_name in cur_cols:
            if col_name not in tgt_cols:
                ops.append(DropColumn(name, col_name))

        cur_idx_names = {i.name for i in cur.indexes}
        tgt_idx_by_name = {i.name: i for i in tgt.indexes}

        for idx_name, idx in tgt_idx_by_name.items():
            if idx_name not in cur_idx_names:
                ops.append(AddIndex(name, idx))

        for idx_name in cur_idx_names:
            if idx_name not in tgt_idx_by_name:
                ops.append(DropIndex(name, idx_name))

    return ops
